feat/array-from2
tutuka00/array-from pull request #2
Opened 2023-09-14 12:03 UTC by tutuka00

2023-09-15 07:57 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-15 07:57 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +                        <?php endif; ?>
ここでif文は、使用せず書きましょう！
$tweetsの代わりに、$satouTweets配列を使用すればOKです！！

2023-09-15 17:30 UTC, tutuka00 commented
ここでif文は、使用せず$tweetsの代わりに、$satouTweets配列を使用し修正したので、
お手隙の際にご確認よろしくお願い致します！

2023-09-18 22:54 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-09-19 14:02 UTC, merged